# Generated by Django 5.1.2 on 2024-10-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('telegram_nickname', models.CharField(max_length=100, verbose_name='Telegram')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('preferred_communication_type', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], max_length=10, verbose_name='PreferredCommunicationType')),
                ('additional_info', models.TextField(verbose_name='Info')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='SiteName')),
                ('site_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='SiteDescription')),
                ('about', models.TextField(verbose_name='About')),
                ('service_list', models.JSONField(verbose_name={'Финансовые консультации для бизнеса', 'диагностика действующего управленческого учета', 'хей'})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('text', models.TextField(verbose_name='Text')),
                ('key_phrase', models.CharField(max_length=200, verbose_name='KeyPhrase')),
                ('tags', models.ManyToManyField(to='portfolio_app.tag')),
            ],
        ),
    ]
