# Generated by Django 5.1.2 on 2024-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='telegram_nickname',
            new_name='telegram',
        ),
        migrations.RemoveField(
            model_name='client',
            name='preferred_communication_type',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
