# Generated by Django 5.1.3 on 2024-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_alter_post_datetime_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(choices=[('AC', 'Active'), ('AR', 'Archived')], default='AC', max_length=10, verbose_name='State'),
        ),
    ]
